const keywords = [
    "Diss na PUT",
    "Proszę się nie spóźniać",
    "GE",
    "WE",
    "just Adaś things",
    "Adaś skończył prezentację",
    "Adaś nie skończył prezentacji",
    "Ktoś zrobił mema z Adasiem",
    "Diss na Polaków",
    "To powinni państwo umieć",
    "Nie każdy musi być inżynierem",
    "Jak się pan nazywa?",
    "Adaś polityk",
    "Laser na monitor",
    "How did we get here",
    "Proszę wpisać sobie spóźnienie",
    "Adasiowi nie podoba się jak inni oznaczają układy",
    "Adaś opisuje jak jest na innych uczelniach",
    "Powtarzanie słowa \"istotne\"",
    "Adaś zbacza z tematu",
    "Adasiowi nie podobają się polskie nazwy",
    "Chujowe audio (przester)",
    "Zdjęcie Adasia na prezentacji",
    "Przeźrocze",
    "Pszeszczeń",
    "Adaś daje plusa",
    "Coś o Gilbercie Strangu/MIT",
    "Prawdziwy inżynier powinien..."
]
